name: 'Run "fcli fod session login" command'
description: 'Run "fcli fod session login" command based on environment variables, auto-logout on job termination'
author: 'Fortify'
runs:
  using: composite
  steps:
    # If not run before: check preconditions, run fcli login command, and run 
    # post-job fcli logout command.
    # Note that the calling action/workflow is responsible for installing fcli
    - uses: fortify/github-action/internal/run-script@main
      if: ${{ !env._FOD_LOGGED_IN }}
      with:
        script: fod-login.sh
        post: fod-logout.sh
          
branding:
  icon: 'shield'
  color: 'blue'

