name: 'Fortify AST Scan'
description: 'Run Fortify AST Scan and upload debug artifacts using actions/upload-artifact@v7 (GitHub.com).'
author: 'Fortify'
inputs:
  debug:
    description: 'Whether to generate & collect debug artifacts; note that these may contain sensitive data like access tokens or credentials. Automatically enabled when workflow is re-run with "Enable debug logging" checked.'
    required: false
    default: 'false'
  debug-artifact-name:
    description: 'Name for the debug artifacts archive; defaults to "fortify-debug-artifacts"'
    required: false
    default: 'fortify-debug-artifacts'
  debug-retention-days:
    description: 'Number of days to retain debug artifacts; defaults to 1 due to sensitivity of data'
    required: false
    default: '1'

runs:
  using: composite
  steps:
    - uses: fortify/github-action/with-github-artifacts@v3.1.0
      with:
        debug: ${{ inputs.debug }}
        debug-artifact-name: ${{ inputs.debug-artifact-name }}
        debug-retention-days: ${{ inputs.debug-retention-days }}

branding:
  icon: 'shield'
  color: 'blue'

