name: 'Fortify AST Scan'
description: 'Find and fix vulnerabilities to build secure software with Fortify Code Security.'
author: 'Fortify'
inputs:
  sast-scan:
    description: 'Run a SAST scan, takes either true or false (default)'
    default: 'false'
    required: false
runs:
  using: composite
  steps:
    - uses: fortify-ps/github-action/fod-sast-scan@main
      if: inputs['sast-scan']=='true' && env.FOD_URL
    - uses: fortify-ps/github-action/sc-sast-scan@main
      if: inputs['sast-scan']=='true' && env.SSC_URL  
        
branding:
  icon: 'shield'
  color: 'blue'

