name: 'Fortify AST Scan'
description: 'Find and fix vulnerabilities to build secure software with Fortify Code Security.'
author: 'Fortify'
#inputs:
runs:
  using: composite
  steps:
    - uses: fortify/github-action/setup@feat/fcli-ci
      with:
        fcli: bootstrapped
        export-path: false
    - run: |
        "${FCLI_CMD}" action run ci
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
branding:
  icon: 'shield'
  color: 'blue'

