name: 'Perform Debricked scan'
description: 'Perform a Debricked Software Composition Analysis (SCA) scan and publish results to SSC'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: fortify/github-action/internal/set-ssc-var-defaults@ghes-workaround
    - uses: fortify/github-action/setup@ghes-workaround
      with:
        export-path: false
        fcli: action-default
        debricked-cli: action-default
    - uses: fortify/github-action/internal/ssc-login@ghes-workaround
    - uses: fortify/github-action/internal/run-script@ghes-workaround
      with:
        script: sc-sast-and-debricked-scan.sh
      env: 
        DO_DEBRICKED_SCAN: true
        DO_SC_SAST_SCAN: false
        
branding:
  icon: 'shield'
  color: 'blue'

