name: 'Run "fcli fod session login" command'
description: 'Run "fcli fod session login" command based on environment variables'
author: 'Fortify'
runs:
  using: composite
  steps:
    # TODO If we wait for scan completion, potentially we could generate a CIToken if 
    #      SSC_USER and SSC_PASSWORD have been set, and then revoke the token once the
    #      scan has been successfully processed on SSC.
    
    # If not run before: check preconditions, run fcli login command, and run 
    # post-job fcli logout command.
    # Note that the calling action/workflow is responsible for installing fcli
    - uses: fortify/github-action/internal/run-script@dev/v2.x
      if: ${{ !env._SC_SAST_LOGGED_IN }}
      with:
        script: sc-sast-login.sh
        post: sc-sast-logout.sh
            
branding:
  icon: 'shield'
  color: 'blue'

