name: 'Package source code & dependencies'
description: 'Package source code & dependencies for SAST & SCA scans'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: fortify/github-action/internal/setup-java-for-sc-client@v1.6.4
    - uses: fortify/github-action/setup@v1.6.4
      with:
        export-path: false
        sc-client: action-default
    - uses: fortify/github-action/internal/run-script@v1.6.4
      with:
        script: package.sh
    - name: Store ScanCentral package
      if: env.DO_PACKAGE_DEBUG == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}-${{ strategy.job-index }}-scancentral-package
        path: package.zip
    - name: Store ScanCentral logs
      if: env.DO_PACKAGE_DEBUG == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}-${{ strategy.job-index }}-scancentral-logs
        path: |
          ~/.fortify/scancentral-*/log/*.log
          ~/AppData/Local/Fortify/scancentral-*/log/*.log
        include-hidden-files: true
        
branding:
  icon: 'shield'
  color: 'blue'

